import * as github from '@actions/github';
import * as fs from 'fs';
import * as path from 'path';
import type { CompositeResult } from './composite';

const COMMENT_MARKER = '<!-- visionsim-action -->';
const BRANCH_NAME = 'visionsim-previews';

type Octokit = ReturnType<typeof github.getOctokit>;

interface UploadedImage {
  url: string;
  altText: string;
  sourceImage: string;
}

/**
 * Ensure the orphan branch exists for hosting preview images.
 */
async function ensureOrphanBranch(octokit: Octokit, owner: string, repo: string): Promise<void> {
  try {
    await octokit.rest.repos.getBranch({ owner, repo, branch: BRANCH_NAME });
  } catch (err: any) {
    if (err.status === 404) {
      // Create orphan branch with an empty commit via the Git Data API
      const blob = await octokit.rest.git.createBlob({
        owner, repo,
        content: Buffer.from('# VisionSim Previews\n\nThis branch hosts preview images generated by the VisionSim GitHub Action.\n').toString('base64'),
        encoding: 'base64',
      });
      const tree = await octokit.rest.git.createTree({
        owner, repo,
        tree: [{ path: 'README.md', mode: '100644', type: 'blob', sha: blob.data.sha }],
      });
      const commit = await octokit.rest.git.createCommit({
        owner, repo,
        message: 'chore: initialize visionsim-previews branch',
        tree: tree.data.sha,
        parents: [],
      });
      await octokit.rest.git.createRef({
        owner, repo,
        ref: `refs/heads/${BRANCH_NAME}`,
        sha: commit.data.sha,
      });
    } else {
      throw err;
    }
  }
}

/**
 * Upload composite images to the orphan branch and return their raw URLs.
 */
async function uploadImages(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  headSha: string,
  composites: CompositeResult[],
): Promise<UploadedImage[]> {
  await ensureOrphanBranch(octokit, owner, repo);

  const uploaded: UploadedImage[] = [];
  const shortSha = headSha.substring(0, 7);

  for (const composite of composites) {
    const content = fs.readFileSync(composite.path);
    const fileName = `pr-${prNumber}/${shortSha}/${path.basename(composite.path)}`;

    // Check if file exists (for update vs create)
    let existingSha: string | undefined;
    try {
      const existing = await octokit.rest.repos.getContent({
        owner, repo, path: fileName, ref: BRANCH_NAME,
      });
      if (!Array.isArray(existing.data) && 'sha' in existing.data) {
        existingSha = existing.data.sha;
      }
    } catch {
      // File doesn't exist yet — that's fine
    }

    await octokit.rest.repos.createOrUpdateFileContents({
      owner, repo,
      path: fileName,
      message: `visionsim: PR #${prNumber} @ ${shortSha}`,
      content: content.toString('base64'),
      branch: BRANCH_NAME,
      ...(existingSha ? { sha: existingSha } : {}),
    });

    const rawUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${BRANCH_NAME}/${fileName}`;
    uploaded.push({
      url: rawUrl,
      altText: composite.altText,
      sourceImage: composite.sourceImage,
    });
  }

  return uploaded;
}

/**
 * Post or update a PR comment with the composite images.
 */
export async function postPRComment(
  token: string,
  composites: CompositeResult[],
): Promise<void> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const prNumber = github.context.payload.pull_request?.number;

  if (!prNumber) {
    // eslint-disable-next-line no-console
    console.log('Not a PR context — skipping comment.');
    return;
  }

  const headSha = github.context.payload.pull_request?.head?.sha || github.context.sha;

  let uploaded: UploadedImage[];
  try {
    uploaded = await uploadImages(octokit, owner, repo, prNumber, headSha, composites);
  } catch (err: any) {
    if (err.status === 403) {
      // Fork PR — fall back to step summary
      // eslint-disable-next-line no-console
      console.log('Cannot upload images (likely a fork PR). Falling back to step summary.');
      await writeStepSummary(composites);
      return;
    }
    throw err;
  }

  // Build comment body
  const body = buildCommentBody(uploaded);

  // Find existing comment
  const comments = await octokit.rest.issues.listComments({
    owner, repo, issue_number: prNumber, per_page: 100,
  });
  const existing = comments.data.find(c => c.body?.includes(COMMENT_MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner, repo, comment_id: existing.id, body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner, repo, issue_number: prNumber, body,
    });
  }
}

/**
 * Create a check run with the composite images.
 */
export async function createCheckRun(
  token: string,
  composites: CompositeResult[],
): Promise<void> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const headSha = github.context.payload.pull_request?.head?.sha || github.context.sha;

  const summary = composites
    .map(c => `- **${path.basename(c.sourceImage)}**: ${c.altText}`)
    .join('\n');

  await octokit.rest.checks.create({
    owner, repo,
    name: 'VisionSim',
    head_sha: headSha,
    conclusion: 'neutral',
    output: {
      title: 'Vision Condition Simulation Results',
      summary: `Rendered ${composites.length} composite(s) across vision conditions.\n\n${summary}`,
    },
  });
}

function buildCommentBody(uploaded: UploadedImage[]): string {
  let body = `${COMMENT_MARKER}\n`;
  body += '## :eye: VisionSim Results\n\n';

  for (const img of uploaded) {
    body += `![${img.altText}](${img.url})\n\n`;
  }

  body += '<details>\n<summary>About this check</summary>\n\n';
  body += 'This comment was generated by the [VisionSim GitHub Action](https://github.com/bloo-berries/blindness-visualizer). ';
  body += 'It renders your screenshots under simulated vision conditions to help catch accessibility issues early.\n\n';
  body += '</details>\n';

  return body;
}

export async function writeStepSummary(composites: CompositeResult[]): Promise<void> {
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryFile) return;

  let md = '## :eye: VisionSim Results\n\n';
  md += `Rendered ${composites.length} composite(s) across vision conditions.\n\n`;
  for (const c of composites) {
    md += `- **${path.basename(c.sourceImage)}**: ${c.altText}\n`;
  }

  fs.appendFileSync(summaryFile, md);
}
