/**
 * Type definitions for visual effects
 * Centralized to avoid circular dependencies
 */

export type ConditionType = 
  | 'protanopia' 
  | 'deuteranopia' 
  | 'tritanopia' 
  | 'protanomaly' 
  | 'deuteranomaly' 
  | 'tritanomaly' 
  | 'hemianopiaLeft'
  | 'hemianopiaRight'
  | 'quadrantanopiaLeft'
  | 'quadrantanopiaRight'
  | 'quadrantanopiaInferior'
  | 'quadrantanopiaSuperior'
  | 'blindnessLeftEye'
  | 'blindnessRightEye'
  | 'bitemporalHemianopia'
  | 'scotoma'
  | 'visualAura'
  | 'visualAuraLeft'
  | 'visualAuraRight'
  | 'visualFloaters'
  | 'visualSnow'
  | 'visualSnowFlashing'
  | 'visualSnowColored'
  | 'visualSnowTransparent'
  | 'visualSnowDense'
  | 'tunnelVision'
  | 'aura'
  | 'glaucoma'
  | 'amd'
  | 'diabeticRetinopathy'
  | 'astigmatism'
  | 'retinitisPigmentosa'
  | 'stargardt'
  | 'nearSighted'
  | 'farSighted'
  | 'monochromacy'
  | 'monochromatic'
  | 'cataracts'
  | 'hallucinations'
  | 'diplopiaMonocular'
  | 'diplopiaBinocular'
  | 'miltonGlaucomaHalos'
  | 'miltonProgressiveVignetting'
  | 'miltonScotomas'
  | 'miltonRetinalDetachment'
  | 'miltonPhotophobia'
  | 'miltonTemporalFieldLoss'
  | 'miltonProgressiveBlindness'
  | 'completeBlindness'
  | 'galileoAcuteHalos'
  | 'galileoSevereBlurring'
  | 'galileoRedEyeEffect'
  | 'galileoExtremePhotophobia'
  | 'galileoCornealHaziness'
  | 'galileoSectoralDefects'
  | 'galileoArcuateScotomas'
  | 'galileoSwissCheeseVision'
  | 'galileoAcuteAttackMode'
  | 'galileoChronicProgression'
  | 'monetCataractsFog'
  | 'monetColorDistortion'
  | 'monetProgressiveLoss'
  | 'monetCataractsProgression'
  | 'vedCompleteBlindness'
  | 'vedSpatialAwareness'
  | 'vedEchoLocation'
  | 'vedAirFlowSensors'
  | 'vedProximityRadar'
  | 'vedTemperatureMapping'
  | 'christineNMOBlur'
  | 'christineSteamyMirror'
  | 'christineLightScatter'
  | 'christineFogOverlay'
  | 'christineFluctuatingVision'
  | 'christineNMOComplete'
  | 'lucyFrostedGlass'
  | 'lucyHeavyBlur'
  | 'lucyDesaturation'
  | 'lucyLightDiffusion'
  | 'lucyTextureOverlay'
  | 'lucyCompleteVision'
  | 'davidLeftEyeBlindness'
  | 'davidRightEyeGlaucoma'
  | 'davidHemisphericVision'
  | 'davidCompleteVision'
  | 'erikRetinoschisisIslands'
  | 'erikIslandFragmentation'
  | 'erikProgressiveLoss'
  | 'erikCompleteBlindness'
  | 'erikScanningBehavior'
  | 'erikCognitiveLoad'
  | 'marlaCentralScotoma'
  | 'marlaPeripheralVision'
  | 'marlaEccentricViewing'
  | 'marlaFillingIn'
  | 'marlaCrowdingEffect'
  | 'marlaStargardtComplete'
  | 'minkaraEndStageComplete'
  | 'minkaraCentralScotoma'
  | 'minkaraRingScotoma'
  | 'minkaraPeripheralIslands'
  | 'minkaraPhotophobia'
  | 'minkaraAchromatopsia'
  | 'minkaraNightBlindness'
  | 'minkaraProgressiveTimeline'
  | 'minkaraChemistryMode'
  | 'joshuaCompleteBlindness'
  | 'joshuaEcholocation'
  | 'joshuaTactileMaps'
  | 'joshuaAudioLandscape'
  | 'joshuaAccessibilityMode'
  | 'joshuaSonification';

export interface VisualEffect {
  id: ConditionType;
  name: string;
  enabled: boolean;
  intensity: number;
  description: string;
}

export type InputSource = 
  | { type: 'webcam' }  // Note: Keeping 'webcam' as the internal type for compatibility
  | { type: 'image'; url: string }
  | { type: 'youtube' };
