// Re-export all famous people filters from the split directory
// This maintains backward compatibility with existing imports

export {
  galileoFilterConfigs,
  monetFilterConfigs,
  christineFilterConfigs,
  lucyFilterConfigs,
  minkaraFilterConfigs,
  joshuaFilterConfigs,
  milaFilterConfigs,
  judiFilterConfigs,
  sugarFilterConfigs,
  generateAmadouFilters,
  stephenFilterConfigs,
  generateDavidBrownFilters,
  generateLexFilters,
  crazzysteveFilterConfigs,
  tofiriFilterConfigs,
  plateauFilterConfigs,
  eulerFilterConfigs,
  heatherFilterConfigs,
  nemethFilterConfigs,
  daredevilFilterConfigs,
  geordiFilterConfigs,
  blindspotFilterConfigs,
  joseCidFilterConfigs,
  tophFilterConfigs,
  customFamousPeopleFilterConfigs,
  davidFilterConfigs,
  marlaFilterConfigs,
  anselmoFilterConfigs,
  margaritaFilterConfigs,
  fujitoraFilterConfigs,
  chirrutFilterConfigs,
  juliaCarpenterFilterConfigs
} from './famousPeopleFilters/index';
