// Re-export all famous people filters from the split directory
// This maintains backward compatibility with existing imports

export {
  generateGalileoFilters,
  generateMonetFilters,
  generateChristineFilters,
  generateLucyFilters,
  generateMinkaraFilters,
  generateJoshuaFilters,
  generateMilaFilters,
  generateJudiFilters,
  generateSugarFilters,
  generateAmadouFilters,
  generateStephenFilters,
  generateDavidBrownFilters,
  generateLexFilters,
  generateCrazzysteveFilters,
  generateTofiriFilters,
  generatePlateauFilters,
  generateEulerFilters,
  generateHeatherFilters,
  generateNemethFilters,
  generateDaredevilFilters,
  generateGeordiFilters,
  generateBlindspotFilters,
  generateJoseCidFilters,
  generateTophFilters,
  generateCustomFamousPeopleFilters,
  generateAnselmoFilters,
  generateMargaritaFilters,
  generateFujitoraFilters,
  generateChirrutFilters,
  generateJuliaCarpenterFilters
} from './famousPeopleFilters/index';
